version: '3'
services:
  react-app:
    image: nws_octobre_frontend
    stdin_open: true
    ports:
      - "8001:3000"

  api:
    image: nws_octobre_backend
    ports:
      - "8000:8000"
    networks:
      - mern-app
    restart: always
networks:
  mern-app:
    driver: bridge